SSRL
cbfinn/gps pull request #68
Opened 2016-12-20 01:07 UTC by tianheyu927

Cleaned up experiments and removed commented code

2016-12-20 07:32 UTC, cbfinn commented on experiments/pr2_mdgps_example/hyperparams.py
> +""" Hyperparameters for PR2 trajectory optimization experiment. """
These should also be removed from this PR.

2016-12-22 08:42 UTC, cbfinn requested changes
I got part of the way through. Remember this should be a *minimal* example of the code in the paper, so please go through the PR *carefully* and thoroughly and remove unused code that isn't part of the paper.

2016-12-22 08:42 UTC, cbfinn commented on experiments/mjc_pointmass_observed/hyperparams.py
> +""" Hyperparameters for MJC 2D navigation policy optimization. """
remove file

2016-12-22 08:42 UTC, cbfinn commented on experiments/mjc_pointmass_observed_ioc/hyperparams.py
> +""" Hyperparameters for MJC 2D navigation policy optimization. """
remove file

2016-12-22 08:42 UTC, cbfinn commented on experiments/mjc_pointmass_observed_mdgps/hyperparams.py
> +""" Hyperparameters for MJC 2D navigation policy optimization. """
remove file

2016-12-22 08:42 UTC, cbfinn commented on experiments/pr2_example/hyperparams.py
> +from gps.algorithm.cost.cost_utils import RAMP_LINEAR, RAMP_FINAL_ONLY, RAMP_CONSTANT, evall1l2term
remove file changes

2016-12-22 08:42 UTC, cbfinn commented on experiments/reacher_ioc_images/hyperparams.py
> +from __future__ import division
you can remove this file.

2016-12-22 08:42 UTC, cbfinn commented on python/gps/agent/agent.py
> +        if GYM_REWARD in self._hyperparams['sensor_dims']:
can you remove the code that references GYM_REWARD?

2016-12-22 08:42 UTC, cbfinn commented on python/gps/agent/config.py
> +AGENT_OPENAI = {}
remove this line

2016-12-22 08:42 UTC, cbfinn commented on python/gps/agent/ros/agent_ros.py
> +        time.sleep(2.0)
remove the change to this line

2016-12-22 08:42 UTC, cbfinn commented on python/gps/algorithm/algorithm_badmm.py
> +        if self._hyperparams['ioc'] and not self._hyperparams['init_demo_policy']:
I think the second part of this if statement shouldn't be there... can you delete it?

2016-12-22 08:42 UTC, cbfinn commented on python/gps/algorithm/algorithm_badmm.py
> +
only one line between code chunks, not two. (not just here -- please look over other code too.)

2016-12-22 08:42 UTC, cbfinn commented on python/gps/algorithm/algorithm_badmm.py
> +
remove this addition

2016-12-22 08:42 UTC, cbfinn commented on python/gps/algorithm/algorithm_badmm.py
> +        multiplier = self._hyperparams['max_ent_traj']
this should be used in this function...

can you fix this?

2016-12-22 08:42 UTC, cbfinn commented on python/gps/algorithm/algorithm_mdgps.py
> +        END_EFFECTOR_POINTS, END_EFFECTOR_POINT_VELOCITIES, \
remove imports that aren't used

2016-12-22 08:42 UTC, cbfinn commented on python/gps/algorithm/algorithm_mdgps.py
> +        else:
do we use multiple policies ever? if not, delete

2016-12-22 08:42 UTC, cbfinn commented on python/gps/algorithm/algorithm_traj_opt.py
> +        # self.policy_opt = self._hyperparams['policy_opt']['type'](
remove

2016-12-22 08:42 UTC, cbfinn commented on python/gps/algorithm/algorithm_traj_opt.py
> +            for i in xrange(self.M):
can we put this code in a util or super class?

2016-12-22 08:42 UTC, cbfinn commented on python/gps/algorithm/algorithm_utils.py
> +    #fd = np.linalg.solve(sigma[:dX, :dX], sigma[:dX, dX:dX+dU]).T
remove

2016-12-22 08:42 UTC, cbfinn commented on python/gps/algorithm/config.py
> +    'ioc': None,  # ICML, MPF, IOCGAN, XENTGAN
update comment to only include ICML option

2016-12-22 08:42 UTC, cbfinn commented on python/gps/algorithm/config.py
> +    'ioc_maxent_iter': -1, # number of iterations to run maxent and IOC for (-1 if all iters)
put comment on line above

2016-12-22 08:42 UTC, cbfinn commented on python/gps/algorithm/config.py
> +    'learning_from_prior': False,
remove?

2016-12-22 08:42 UTC, cbfinn commented on python/gps/algorithm/config.py
> +    'global_cost': True,
remove? (we always do global)

2016-12-22 08:42 UTC, cbfinn commented on python/gps/algorithm/config.py
> +    'bootstrap': False,
remove?

2016-12-22 08:42 UTC, cbfinn commented on python/gps/algorithm/config.py
> +    'multiple_policy': False,
remove?

2016-12-22 08:42 UTC, cbfinn commented on python/gps/algorithm/config.py
> +    'num_policies': 1,
remove?

2016-12-22 08:42 UTC, cbfinn commented on python/gps/algorithm/cost/config.py
> +    # 'data_type': None, # must be set
remove

2016-12-22 08:42 UTC, cbfinn commented on python/gps/algorithm/cost/cost_fk_blocktouch.py
> +""" This file defines the forward kinematics cost function. """
remove file

2016-12-22 08:42 UTC, cbfinn commented on python/gps/algorithm/cost/cost_ioc_vision_tf.py
> +""" This file defines neural network cost function. """
remove file

2016-12-22 08:42 UTC, cbfinn commented on python/gps/algorithm/cost/cost_state.py
> +        # Allocate space for derivatives (full state)
remove changes in this file.

2016-12-22 08:42 UTC, cbfinn commented on python/gps/algorithm/cost/cost_utils.py
> +def construct_quad_cost_net(dim_hidden=None, dim_input=27, T=100,
clean this function to remove duplicated code.

2016-12-22 08:42 UTC, cbfinn commented on python/gps/algorithm/cost/ioc_layers.py
> +class GaussianProcessPriors(caffe.Layer):
remove GP code

2016-12-22 08:42 UTC, cbfinn commented on python/gps/algorithm/cost/ioc_layers.py
> +class SigmoidMPFLoss(caffe.Layer):
remove code that we don't use.

2016-12-22 08:48 UTC, tianheyu927 commented on experiments/mjc_pointmass_observed/hyperparams.py
> +""" Hyperparameters for MJC 2D navigation policy optimization. """
I think this is the obstacle experiment in the paper and so are the following two files.

2016-12-27 04:02 UTC, cbfinn requested changes
Here are some initial comments. Let me know when you're done or almost done with these.

2016-12-27 04:02 UTC, cbfinn commented on python/gps/algorithm/algorithm_utils.py
> -
this line shouldn't be deteled. There should be two lines between functions.

2016-12-27 04:02 UTC, cbfinn commented on python/gps/algorithm/algorithm_utils.py
> -
also should be two lines between imports and the class

2016-12-27 04:02 UTC, cbfinn commented on python/gps/algorithm/cost/config.py
> -
should be two lines here too.

2016-12-27 04:02 UTC, cbfinn commented on python/gps/algorithm/cost/cost_fk.py
> +        if self._hyperparams.get('use_jacobian', True):
this code change should be reverted, I think.

2016-12-27 04:02 UTC, cbfinn commented on python/gps/algorithm/cost/cost_utils.py
> +from gps.algorithm.cost import __file__ as current_path
are these new imports used in this file? if not, remove.

2016-12-27 04:02 UTC, cbfinn commented on python/gps/algorithm/dynamics/dynamics_lr.py
> +            # sigma[it, it] += np.eye(dX+dU)*self._hyperparams['regularization']
remove.

2016-12-27 04:02 UTC, cbfinn commented on python/gps/algorithm/dynamics/dynamics_lr_prior.py
> +            # sig_reg[it, it] = np.eye(dX+dU)*self._hyperparams['regularization']
remove.

2016-12-27 04:02 UTC, cbfinn commented on python/gps/algorithm/policy/tf_policy.py
> +        #ops.reset_default_graph()  # we need to destroy the default graph before re_init or checkpoint won't restore.
remove?

2016-12-27 04:02 UTC, cbfinn commented on python/gps/algorithm/policy_opt/policy_opt_tf.py
> +        # self.policy.scale = np.eye(len(self.x_idx))
remove.

2016-12-27 04:02 UTC, cbfinn commented on python/gps/algorithm/traj_opt/traj_opt_lqr_python_state_dynamics.py
> +""" This file defines code for iLQG-based trajectory optimization. """
what does this file do? / where is it used? If not used, remove.

2016-12-27 04:02 UTC, cbfinn commented on python/gps/gps_main.py
> +    import matplotlib.pyplot as plt
don't put imports here

2016-12-27 04:02 UTC, cbfinn commented on src/proto/gps.proto
> +  GYM_DATA = 18;
remove gym stuff

2016-12-27 04:02 UTC, cbfinn commented on python/gps/utility/data_logger.py
> +def open_zip(filename, mode='r'):
remove zip stuff

2016-12-27 04:02 UTC, cbfinn commented on src/gps_agent_pkg/launch/pr2_gazebo_no_controller.launch
> +  <include file="$(find gazebo_ros)/launch/empty_world.launch">
can you remove this change?

2016-12-27 04:02 UTC, cbfinn commented on python/gps/utility/visualization.py
> +    import random
move import to the top

2016-12-27 04:02 UTC, cbfinn commented on python/gps/utility/visualization.py
> +    algorithm_demo = gps.data_logger.unpickle(gps._hyperparams['common']['demo_exp_dir'] + 'data_files/algorithm_itr_09.pkl') # Assuming not using 4 policies
Isn't this value in the hyperparams directory as demo_controller_file, or something similar?

2016-12-27 04:02 UTC, cbfinn commented on python/gps/utility/visualization.py
> +                        verbose=(i < gps._hyperparams['verbose_trials']), noisy=True
put noisy on next line to be within line length limit (and since it is already broken up)

2016-12-27 04:02 UTC, cbfinn commented on python/gps/utility/visualization.py
> +                    verbose=(i < gps._hyperparams['verbose_trials']), noisy=True, record_image=True, \
make it within the line limit. Also the "\" is unnecessary (since this code is within parantheses)

2016-12-27 04:02 UTC, cbfinn commented on python/gps/utility/visualization.py
> +    ioc_conditions = [np.array([np.log10(agent_config['density_range'][i]), 0.]) \
backslash unnecessary

2016-12-27 04:02 UTC, cbfinn commented on python/gps/utility/visualization.py
> +    success_rate_ioc = np.mean(successes[0], axis=0)
can you make these four lines into one line of code:
success_rates = [np.mean(success, axis=0) for success in successes]

2016-12-27 04:02 UTC, cbfinn commented on python/gps/utility/visualization.py
> +    plt.savefig(gps._data_files_dir + 'distribution_of_sample_conditions_average_curve.png')
Nit: can you make this name shorter? e.g. sample_conds_distr.png

2016-12-27 04:02 UTC, cbfinn commented on python/gps/utility/visualization.py
> +    algorithm_ioc = gps.data_logger.unpickle(gps._data_files_dir + 'algorithm_itr_%02d' % pol_iter + '.pkl')
maybe shorten to alg_ioc, alg_sup, etc?

2016-12-27 04:02 UTC, cbfinn commented on python/gps/utility/visualization.py
> +    from gps.utility.general_utils import mkdir_p
put import at top

2016-12-27 04:02 UTC, cbfinn commented on python/gps/utility/visualization.py
> +    pol_ioc = algorithm_ioc.policy_opt.policy
why not make a list of algorithms, then use a list iteration to make a list of policies -- policies = [alg.policy_opt.policy for alg in algorithms]

2016-12-27 04:02 UTC, cbfinn commented on python/gps/utility/visualization.py
> +    print "ioc mean: " + repr(success_rate_ioc.mean())
to make this more concise, maybe combine each pair into one line --
print 'ioc: ' + repr(success_rate_ioc.mean()) + ', ' + repr(success_rate_ioc)

2016-12-27 04:02 UTC, cbfinn commented on python/gps/utility/generate_demo.py
> +import argparse
are all these imports needed? if not, remove unused imports?

2016-12-27 04:02 UTC, cbfinn commented on python/gps/utility/generate_demo.py
> +        def generate(self, demo_file, ioc_agent):
can you split up this function into helper functions to make it more readable?

2016-12-27 04:02 UTC, cbfinn commented on python/gps/utility/generate_demo.py
> +                sample_end_effectors = [cur_samples[i].get_X()[:,pos_idx] for i in xrange(len(cur_samples))]
can you make a general util function for computing these distances? (and use it both here and in the algorithm files, and whereever else we compute this)

2016-12-27 04:02 UTC, cbfinn commented on python/gps/utility/demo_utils.py
> +		# Make the uniform distribution to be [-0.12, 0.12] for learning from prior. For peg ioc, this should be [-0.1, -0.1].
update comment

2016-12-27 04:02 UTC, cbfinn commented on python/gps/utility/demo_utils.py
> +def compute_distance(target_end_effector, sample_list, end_effector_idxs=range(0,3)):
here's the util function! Let's move this into general_utils.

2016-12-27 04:02 UTC, cbfinn commented on python/gps/utility/demo_utils.py
> +        dists_to_target = [np.nanmin(np.sqrt(np.sum((sample.get(END_EFFECTOR_POINTS)[:, :3] - \
this should use the util function!

2016-12-27 04:02 UTC, cbfinn commented on python/gps/utility/data_logger.py
> +def open_zip(filename, mode='r'):
(all the changes in this file)

2017-01-01 23:43 UTC, cbfinn requested changes
Added a bunch of comments. I think it's close.

In your next code revision, can you add some instructions for how to run the examples in the paper, and create the plots?

2017-01-01 23:43 UTC, cbfinn commented on mjc_models/reacher.xml
> +		<!-- Target -->
remove commented out code here.

2017-01-01 23:43 UTC, cbfinn commented on mjc_models/reacher_img.xml
> +		<!-- Target -->
remove commented out code.

2017-01-01 23:43 UTC, cbfinn commented on python/gps/agent/mjc/agent_mjc.py
> +        if self._hyperparams['hardcoded_linear_dynamics']:
can remove hardcoded linear dynamics.

2017-01-01 23:43 UTC, cbfinn commented on python/gps/agent/mjc/agent_mjc.py
> +                    if 'hardcoded_linear_dynamics' in self._hyperparams and self._hyperparams['hardcoded_linear_dynamics']:
can remove hard coded linear dynamics

2017-01-01 23:43 UTC, cbfinn commented on python/gps/agent/mjc/agent_mjc.py
> +            # TODO is this correct?
remove this comment.

2017-01-01 23:43 UTC, cbfinn commented on python/gps/gps_main.py
> +        import numpy as np
put imports at the top of the file.

2017-01-01 23:43 UTC, cbfinn commented on python/gps/gps_main.py
> +                    # TODO - need to add these to lines back in when we move to mdgps
remove comment?

2017-01-01 23:43 UTC, cbfinn commented on python/gps/gps_main.py
> +            # Note - this update doesn't use the cost of the samples. It uses
remove this comment, since it is no longer true.

2017-01-01 23:43 UTC, cbfinn commented on python/gps/gps_main.py
> +            if False: #self.using_ioc():
Change to "if self.using_ioc()".

2017-01-01 23:43 UTC, cbfinn commented on python/gps/gps_main.py
> +    SEED = hyperparams.seed
what if hyperparams.seed doesn't exist? Should add logic to handle that.

2017-01-01 23:43 UTC, cbfinn commented on python/gps/utility/general_utils.py
> +from collections import Mapping, Container
move imports to top of file

2017-01-01 23:43 UTC, cbfinn commented on python/gps/utility/generate_demo.py
> +            if 'filter_demos' in agent_config:
The code here and below (in the elif) seems very similar. Can they be merged?

2017-01-01 23:43 UTC, cbfinn commented on python/gps/algorithm/algorithm.py
> +            var_limit = 2 #self._hyperparams['policy_synthetic_samples_distro_fix_bound'] # Assuming to be 2
remove commented out code.

2017-01-01 23:43 UTC, cbfinn commented on python/gps/algorithm/algorithm.py
> +            # TODO - maybe symmetrize sigma?
remove todo

2017-01-01 23:43 UTC, cbfinn commented on python/gps/algorithm/algorithm.py
> +        # TODO - this is a weird hack that is wrong, and has been in the code for awhile.
remove TODO

2017-01-01 23:43 UTC, cbfinn commented on python/gps/algorithm/algorithm.py
> +        # TODO - make these changes in other algorithm objects too.
what is this TODO?

2017-01-01 23:43 UTC, cbfinn commented on python/gps/algorithm/algorithm.py
> +        # For IOC+vision, recompute demoX here using self.cost. Assumes
remove commented out code.

2017-01-01 23:43 UTC, cbfinn commented on python/gps/algorithm/cost/tf_cost_utils.py
> +    inputs['demo_obs'] = demo_obs = tf.placeholder(tf.float32, shape=(demo_batch_size, T, dim_input))
a lot of the code here and in the below functions is copied. Can we reuse with helper functions?

2017-01-14 01:48 UTC, tianheyu927 commented on python/gps/algorithm/cost/cost_fk.py
> +        if self._hyperparams.get('use_jacobian', True):
I put this change back since if we extract samples from saved pickle files, the jacobians are missing.

2017-01-20 01:10 UTC, merged