PILQR
cbfinn/gps pull request #80
Opened 2017-03-21 05:08 UTC by zhangmarvin

This PR implements the PILQR algorithm as described in [1] as well as the MDGPS extension. Three experiments are provided: a pointmass example with discontinuous costs, as well as the gripper pusher trajectory optimization and door opening policy optimization experiments from [1].

The main contributions are as follows:

- Algorithm files `algorithm_mdgps_pilqr.py`, `algorithm_traj_opt_pilqr.py`, and `traj_opt_pilqr.py`. In addition, `traj_opt_lqr_python.py` and `traj_opt_pi2.py` have been modified heavily to support the algorithm detailed in [1].
- Experiment files provided in the `mjc_disc_cost_example`, `mjc_gripper_pusher`, and `mjc_door_opening` experiment directories along with the MuJoCo XML files.
- Supporting files for new cost functions (note that there is one TODO left here that I believe is out of the scope of this PR), TensorFlow network construction, and KL-divergence computation.

There are various other minor changes that should be relatively self-explanatory given the diffs below, mostly cosmetic and some functional.

Huge thanks to collaborators @Lolu28 and @ychebotar for helping to get this out the door.

[1] Y. Chebotar, et. al. "Combining model-based and model-free updates for trajectory-centric reinforcement learning." arXiv pre-print arXiv:1703.03078.

2017-03-21 15:51 UTC, cbfinn commented
Thanks @zhangmarvin ! I'll probably get to this review this weekend.

2017-03-28 18:48 UTC, cbfinn requested changes
Here are comments, mostly minor. The code is very clean - thank you!

I think it would be good to have some sort of README that is associated with this method, and explains how to reproduce your simulated experiments in the paper.

(e.g. see the readme in the SSRL branch.)

2017-03-28 18:48 UTC, cbfinn commented on python/gps/algorithm/algorithm_mdgps_pilqr.py
> +        if not augment:
maybe add a comment here for what this means

2017-03-28 18:48 UTC, cbfinn commented on python/gps/algorithm/algorithm_traj_opt_pilqr.py
> +        pdpc = self.traj_opt.estimate_cost(
For readability, maybe add comment like "# previous dynamics, previous controller" here

2017-03-28 18:48 UTC, cbfinn commented on python/gps/algorithm/algorithm_traj_opt_pilqr.py
> +                    if res/act > self._hyperparams['step_rule_res_ratio_dec']:
nitpic: there should be spaces around the "/"

2017-03-28 18:48 UTC, cbfinn commented on python/gps/algorithm/algorithm_traj_opt_pilqr.py
> +        return self._compute_costs(self.cur[m].traj_distr, m, eta, augment)
Why not just have a single function that sets `traj_distr = self.cur[m].traj_distr` at the top?

2017-03-28 18:48 UTC, cbfinn commented on python/gps/algorithm/cost/cost_fk_blocktouch.py
> +# TODO: This cost function is hard-coded and not easy to generalize.
Is this true? If so, can you put inline comments in parts where it is hard-coded? (in case someone wants to use it for a different scenario)

2017-03-28 18:48 UTC, cbfinn commented on python/gps/algorithm/cost/cost_fk_blocktouch.py
> +class CostFKBlock(Cost):
Can you add a brief description of this cost function? (like the binary cost description)

2017-03-28 18:48 UTC, cbfinn commented on python/gps/algorithm/policy_opt/tf_model_example.py
> +def tf_network(dim_input=27, dim_output=7, batch_size=25, network_config=None):
Can we just replace example_tf_network with this?

2017-03-28 18:48 UTC, cbfinn commented on python/gps/algorithm/traj_opt/config.py
> +    'min_eta': 1e-8,
How does this change affect other experiments?

2017-03-28 18:48 UTC, cbfinn commented on python/gps/algorithm/traj_opt/traj_opt_pi2.py
> +               fixed_eta=None, use_fixed_eta=False, costs=None):
update docstring

2017-03-28 18:48 UTC, cbfinn commented on python/gps/algorithm/traj_opt/traj_opt_pi2.py
> +                   fixed_eta=None, use_fixed_eta=False):
update docstring

2017-03-28 18:48 UTC, cbfinn commented on python/gps/algorithm/traj_opt/traj_opt_pi2.py
> +        fail = True
maybe add comment for what fail is.

2017-03-28 18:48 UTC, cbfinn commented on python/gps/algorithm/traj_opt/traj_opt_utils.py
> +def traj_distr_kl(new_mu, new_sigma, new_traj_distr, prev_traj_distr, tot=True):
update docstring

2017-03-28 18:48 UTC, cbfinn commented on python/gps/algorithm/traj_opt/traj_opt_utils.py
> +def traj_distr_kl_alt(new_mu, new_sigma, new_traj_distr, prev_traj_distr, tot=True):
add description of what this is, and ideally also a docstring

2017-03-28 18:48 UTC, cbfinn commented on python/gps/algorithm/traj_opt/traj_opt_utils.py
> +def approximated_cost(sample_list, traj_distr, traj_info):
add description and docstring

2017-03-28 18:48 UTC, cbfinn commented on python/gps/algorithm/policy_opt/tf_model_example.py
> +        batch_size: Batch size.
update docstring

2017-03-28 18:48 UTC, cbfinn commented on python/gps/algorithm/traj_opt/traj_opt_lqr_python.py
> +        if self._update_in_bwd_pass:
This PR adds quite a lot of code to the backward function. Would it make sense to make it more modular?

2017-03-28 18:48 UTC, cbfinn commented on python/gps/algorithm/traj_opt/traj_opt_lqr_python.py
> +    def _conv_check(self, con, kl_step):
maybe add brief description of what this is.

2017-03-28 21:44 UTC, zhangmarvin commented
Thanks Chelsea! I'll get to these comments tonight or tomorrow and revise
accordingly. Is it good to merge afterwards, or would you (or someone else)
want another pass?

Marvin


On Mar 28, 2017 2:48 PM, "Chelsea Finn" <notifications@github.com> wrote:

> *@cbfinn* requested changes on this pull request.
>
> Here are comments, mostly minor. The code is very clean - thank you!
>
> I think it would be good to have some sort of README that is associated
> with this method, and explains how to reproduce your simulated experiments
> in the paper.
>
> (e.g. see the readme in the SSRL branch.)
> ------------------------------
>
> In python/gps/algorithm/algorithm_mdgps_pilqr.py
> <https://github.com/cbfinn/gps/pull/80#discussion_r108499710>:
>
> > +            for m in range(self.M):
> +                AlgorithmTrajOptPILQR._stepadjust(self, m)
> +		
> +        self._update_trajectories()
> +
> +        # S-step
> +        self._update_policy()
> +
> +        # Prepare for next iteration
> +        self._advance_iteration_variables()
> +
> +
> +    def compute_costs_constrained(self, traj_distr, m, eta, augment=True):
> +        """ Compute cost estimates used in the LQR backward pass. """
> +        traj_info, traj_distr = self.cur[m].traj_info, traj_distr
> +        if not augment:
>
> maybe add a comment here for what this means
> ------------------------------
>
> In python/gps/algorithm/algorithm_traj_opt_pilqr.py
> <https://github.com/cbfinn/gps/pull/80#discussion_r108500672>:
>
> > +        m: condition
> +        pdpc: previous dynamics-previous controller cost
> +        pdcc: previous dynamics-current controller cost
> +        cdcc: current dynamics-current controller cost
> +        pmc: previous actual cost
> +        cmc: current actual cost
> +        cur_res:
> +        """
> +
> +    def _stepadjust(self, m):
> +        """
> +        Calculate new step sizes.
> +        Args:
> +            m: Condition
> +        """
> +        pdpc = self.traj_opt.estimate_cost(
>
> For readability, maybe add comment like "# previous dynamics, previous
> controller" here
> ------------------------------
>
> In python/gps/algorithm/algorithm_traj_opt_pilqr.py
> <https://github.com/cbfinn/gps/pull/80#discussion_r108500841>:
>
> > +            self.cur[m].step_mult = self.prev[m].step_mult
> +        elif self._hyperparams['step_rule'] == 'res_percent':
> +            cur_res_sum = np.mean(np.sum(np.abs(cur_res), axis=1))
> +            act_sum = np.mean(np.sum(np.abs(self.cur[m].cs), axis=1))
> +            # Print cost details.
> +            LOGGER.debug(
> +                    'Cur residuals: %f. Residuals percentage: %f',
> +                    cur_res_sum, cur_res_sum/act_sum*100
> +            )
> +            if self.traj_opt.cons_per_step:
> +                T = cur_res.shape[1]
> +                new_mult = np.ones(T)
> +                for t in range(T):
> +                    res = np.mean(np.sum(np.abs(cur_res[:, t:]), axis=1))
> +                    act = np.mean(np.sum(np.abs(self.cur[m].cs[:, t:]), axis=1))
> +                    if res/act > self._hyperparams['step_rule_res_ratio_dec']:
>
> nitpic: there should be spaces around the "/"
> ------------------------------
>
> In python/gps/algorithm/algorithm_traj_opt_pilqr.py
> <https://github.com/cbfinn/gps/pull/80#discussion_r108501232>:
>
> > +                    K[t, :, :].T.dot(ipc[t, :, :]).dot(K[t, :, :]),
> +                    -K[t, :, :].T.dot(ipc[t, :, :])
> +                ]),
> +                np.hstack([
> +                    -ipc[t, :, :].dot(K[t, :, :]), ipc[t, :, :]
> +                ])
> +            ])
> +            fcv[t, :] += eta / (eta + multiplier) * np.hstack([
> +                K[t, :, :].T.dot(ipc[t, :, :]).dot(k[t, :]),
> +                -ipc[t, :, :].dot(k[t, :])
> +            ])
> +
> +        return fCm, fcv
> +
> +    def compute_costs(self, m, eta, augment=True):
> +        return self._compute_costs(self.cur[m].traj_distr, m, eta, augment)
>
> Why not just have a single function that sets traj_distr =
> self.cur[m].traj_distr at the top?
> ------------------------------
>
> In python/gps/algorithm/cost/cost_fk_blocktouch.py
> <https://github.com/cbfinn/gps/pull/80#discussion_r108501864>:
>
> > @@ -0,0 +1,56 @@
> +# TODO: This cost function is hard-coded and not easy to generalize.
>
> Is this true? If so, can you put inline comments in parts where it is
> hard-coded? (in case someone wants to use it for a different scenario)
> ------------------------------
>
> In python/gps/algorithm/cost/cost_fk_blocktouch.py
> <https://github.com/cbfinn/gps/pull/80#discussion_r108501953>:
>
> > @@ -0,0 +1,56 @@
> +# TODO: This cost function is hard-coded and not easy to generalize.
> +import copy
> +
> +import numpy as np
> +
> +from gps.algorithm.cost.config import COST_FK
> +from gps.algorithm.cost.cost import Cost
> +from gps.algorithm.cost.cost_utils import get_ramp_multiplier
> +from gps.proto.gps_pb2 import JOINT_ANGLES, END_EFFECTOR_POINTS, \
> +        END_EFFECTOR_POINT_JACOBIANS
> +
> +
> +class CostFKBlock(Cost):
>
> Can you add a brief description of this cost function? (like the binary
> cost description)
> ------------------------------
>
> In python/gps/algorithm/policy_opt/tf_model_example.py
> <https://github.com/cbfinn/gps/pull/80#discussion_r108502377>:
>
> > @@ -90,6 +90,29 @@ def example_tf_network(dim_input=27, dim_output=7, batch_size=25, network_config
>      return TfMap.init_from_lists([nn_input, action, precision], [mlp_applied], [loss_out]), fc_vars, []
>
>
> +def tf_network(dim_input=27, dim_output=7, batch_size=25, network_config=None):
>
> Can we just replace example_tf_network with this?
> ------------------------------
>
> In python/gps/algorithm/traj_opt/config.py
> <https://github.com/cbfinn/gps/pull/80#discussion_r108502519>:
>
> > @@ -6,13 +6,28 @@
>      # Dual variable updates for non-PD Q-function.
>      'del0': 1e-4,
>      'eta_error_threshold': 1e16,
> -    'min_eta': 1e-4,
> +    'min_eta': 1e-8,
>
> How does this change affect other experiments?
> ------------------------------
>
> In python/gps/algorithm/traj_opt/traj_opt_pi2.py
> <https://github.com/cbfinn/gps/pull/80#discussion_r108502751>:
>
> > @@ -39,7 +41,8 @@ def __init__(self, hyperparams):
>          self._covariance_damping = self._hyperparams['covariance_damping']
>          self._min_temperature = self._hyperparams['min_temperature']
>
> -    def update(self, m, algorithm):
> +    def update(self, m, algorithm, use_lqr_actions=False,
> +               fixed_eta=None, use_fixed_eta=False, costs=None):
>
> update docstring
> ------------------------------
>
> In python/gps/algorithm/traj_opt/traj_opt_pi2.py
> <https://github.com/cbfinn/gps/pull/80#discussion_r108502840>:
>
> >
> -    def update_pi2(self, samples, costs, mean_old, cov_old):
> +    def update_pi2(self, samples, costs, mean_old, cov_old,
> +                   fixed_eta=None, use_fixed_eta=False):
>
> update docstring
> ------------------------------
>
> In python/gps/algorithm/traj_opt/traj_opt_pi2.py
> <https://github.com/cbfinn/gps/pull/80#discussion_r108502937>:
>
> > -                    cov_new[t])) / len(cov_old[t])
> -                mult = np.power(mult, 1 / self._covariance_damping)
> -                cov_new[t] = mult * cov_old[t]
> -
> -            # Compute covariance inverse and cholesky decomposition.
> -            inv_cov_new[t] = sp.linalg.inv(cov_new[t])
> -            chol_cov_new[t] = sp.linalg.cholesky(cov_new[t])
> -
> -        return mean_new, cov_new, inv_cov_new, chol_cov_new
> +        etas = np.zeros(T)
> +
> +        del_ = self._hyperparams['del0']
> +        if self._hyperparams['pi2_cons_per_step']:
> +            del_ = np.ones(T) * del_
> +
> +        fail = True
>
> maybe add comment for what fail is.
> ------------------------------
>
> In python/gps/algorithm/traj_opt/traj_opt_utils.py
> <https://github.com/cbfinn/gps/pull/80#discussion_r108503207>:
>
> >
> - [...]

2017-03-28 22:32 UTC, cbfinn commented
I'll take another quick pass.

On Tue, Mar 28, 2017 at 2:44 PM, Marvin Zhang <notifications@github.com>
wrote:

> Thanks Chelsea! I'll get to these comments tonight or tomorrow and revise
> accordingly. Is it good to merge afterwards, or would you (or someone else)
> want another pass?
>
> Marvin
>
>
> On Mar 28, 2017 2:48 PM, "Chelsea Finn" <notifications@github.com> wrote:
>
> > *@cbfinn* requested changes on this pull request.
> >
> > Here are comments, mostly minor. The code is very clean - thank you!
> >
> > I think it would be good to have some sort of README that is associated
> > with this method, and explains how to reproduce your simulated
> experiments
> > in the paper.
> >
> > (e.g. see the readme in the SSRL branch.)
> > ------------------------------
> >
> > In python/gps/algorithm/algorithm_mdgps_pilqr.py
> > <https://github.com/cbfinn/gps/pull/80#discussion_r108499710>:
> >
> > > + for m in range(self.M):
> > + AlgorithmTrajOptPILQR._stepadjust(self, m)
> > +
> > + self._update_trajectories()
> > +
> > + # S-step
> > + self._update_policy()
> > +
> > + # Prepare for next iteration
> > + self._advance_iteration_variables()
> > +
> > +
> > + def compute_costs_constrained(self, traj_distr, m, eta, augment=True):
> > + """ Compute cost estimates used in the LQR backward pass. """
> > + traj_info, traj_distr = self.cur[m].traj_info, traj_distr
> > + if not augment:
> >
> > maybe add a comment here for what this means
> > ------------------------------
> >
> > In python/gps/algorithm/algorithm_traj_opt_pilqr.py
> > <https://github.com/cbfinn/gps/pull/80#discussion_r108500672>:
> >
> > > + m: condition
> > + pdpc: previous dynamics-previous controller cost
> > + pdcc: previous dynamics-current controller cost
> > + cdcc: current dynamics-current controller cost
> > + pmc: previous actual cost
> > + cmc: current actual cost
> > + cur_res:
> > + """
> > +
> > + def _stepadjust(self, m):
> > + """
> > + Calculate new step sizes.
> > + Args:
> > + m: Condition
> > + """
> > + pdpc = self.traj_opt.estimate_cost(
> >
> > For readability, maybe add comment like "# previous dynamics, previous
> > controller" here
> > ------------------------------
> >
> > In python/gps/algorithm/algorithm_traj_opt_pilqr.py
> > <https://github.com/cbfinn/gps/pull/80#discussion_r108500841>:
> >
> > > + self.cur[m].step_mult = self.prev[m].step_mult
> > + elif self._hyperparams['step_rule'] == 'res_percent':
> > + cur_res_sum = np.mean(np.sum(np.abs(cur_res), axis=1))
> > + act_sum = np.mean(np.sum(np.abs(self.cur[m].cs), axis=1))
> > + # Print cost details.
> > + LOGGER.debug(
> > + 'Cur residuals: %f. Residuals percentage: %f',
> > + cur_res_sum, cur_res_sum/act_sum*100
> > + )
> > + if self.traj_opt.cons_per_step:
> > + T = cur_res.shape[1]
> > + new_mult = np.ones(T)
> > + for t in range(T):
> > + res = np.mean(np.sum(np.abs(cur_res[:, t:]), axis=1))
> > + act = np.mean(np.sum(np.abs(self.cur[m].cs[:, t:]), axis=1))
> > + if res/act > self._hyperparams['step_rule_res_ratio_dec']:
> >
> > nitpic: there should be spaces around the "/"
> > ------------------------------
> >
> > In python/gps/algorithm/algorithm_traj_opt_pilqr.py
> > <https://github.com/cbfinn/gps/pull/80#discussion_r108501232>:
> >
> > > + K[t, :, :].T.dot(ipc[t, :, :]).dot(K[t, :, :]),
> > + -K[t, :, :].T.dot(ipc[t, :, :])
> > + ]),
> > + np.hstack([
> > + -ipc[t, :, :].dot(K[t, :, :]), ipc[t, :, :]
> > + ])
> > + ])
> > + fcv[t, :] += eta / (eta + multiplier) * np.hstack([
> > + K[t, :, :].T.dot(ipc[t, :, :]).dot(k[t, :]),
> > + -ipc[t, :, :].dot(k[t, :])
> > + ])
> > +
> > + return fCm, fcv
> > +
> > + def compute_costs(self, m, eta, augment=True):
> > + return self._compute_costs(self.cur[m].traj_distr, m, eta, augment)
> >
> > Why not just have a single function that sets traj_distr =
> > self.cur[m].traj_distr at the top?
> > ------------------------------
> >
> > In python/gps/algorithm/cost/cost_fk_blocktouch.py
> > <https://github.com/cbfinn/gps/pull/80#discussion_r108501864>:
> >
> > > @@ -0,0 +1,56 @@
> > +# TODO: This cost function is hard-coded and not easy to generalize.
> >
> > Is this true? If so, can you put inline comments in parts where it is
> > hard-coded? (in case someone wants to use it for a different scenario)
> > ------------------------------
> >
> > In python/gps/algorithm/cost/cost_fk_blocktouch.py
> > <https://github.com/cbfinn/gps/pull/80#discussion_r108501953>:
> >
> > > @@ -0,0 +1,56 @@
> > +# TODO: This cost function is hard-coded and not easy to generalize.
> > +import copy
> > +
> > +import numpy as np
> > +
> > +from gps.algorithm.cost.config import COST_FK
> > +from gps.algorithm.cost.cost import Cost
> > +from gps.algorithm.cost.cost_utils import get_ramp_multiplier
> > +from gps.proto.gps_pb2 import JOINT_ANGLES, END_EFFECTOR_POINTS, \
> > + END_EFFECTOR_POINT_JACOBIANS
> > +
> > +
> > +class CostFKBlock(Cost):
> >
> > Can you add a brief description of this cost function? (like the binary
> > cost description)
> > ------------------------------
> >
> > In python/gps/algorithm/policy_opt/tf_model_example.py
> > <https://github.com/cbfinn/gps/pull/80#discussion_r108502377>:
> >
> > > @@ -90,6 +90,29 @@ def example_tf_network(dim_input=27, dim_output=7,
> batch_size=25, network_config
> > return TfMap.init_from_lists([nn_input, action, precision],
> [mlp_applied], [loss_out]), fc_vars, []
> >
> >
> > +def tf_network(dim_input=27, dim_output=7, batch_size=25,
> network_config=None):
> >
> > Can we just replace example_tf_network with this?
> > ------------------------------
> >
> > In python/gps/algorithm/traj_opt/config.py
> > <https://github.com/cbfinn/gps/pull/80#discussion_r108502519>:
> >
> > > @@ -6,13 +6,28 @@
> > # Dual variable updates for non-PD Q-function.
> > 'del0': 1e-4,
> > 'eta_error_threshold': 1e16,
> > - 'min_eta': 1e-4,
> > + 'min_eta': 1e-8,
> >
> > How does this change affect other experiments?
> > ------------------------------
> >
> > In python/gps/algorithm/traj_opt/traj_opt_pi2.py
> > <https://github.com/cbfinn/gps/pull/80#discussion_r108502751>:
> >
> > > @@ -39,7 +41,8 @@ def __init__(self, hyperparams):
> > self._covariance_damping = self._hyperparams['covariance_damping']
> > self._min_temperature = self._hyperparams['min_temperature']
> >
> > - def update(self, m, algorithm):
> > + def update(self, m, algorithm, use_lqr_actions=False,
> > + fixed_eta=None, use_fixed_eta=False, costs=None):
> >
> > update docstring
> > ------------------------------
> >
> > In python/gps/algorithm/traj_opt/traj_opt_pi2.py
> > <https://github.com/cbfinn/gps/pull/80#discussion_r108502840>:
> >
> > >
> > - def update_pi2(self, samples, costs, mean_old, cov_old):
> > + def update_pi2(self, samples, costs, mean_old, cov_old,
> > + fixed_eta=None, use_fixed_eta=False):
> >
> > update docstring
> > ------------------------------
> >
> > In python/gps/algorithm/traj_opt/traj_opt_pi2.py
> > <https://github.com/cbfinn/gps/pull/80#discussion_r108502937>:
> >
> > > - cov_new[t])) / len(cov_old[t])
> > - mult = np.power(mult, 1 / self._covariance_damping)
> > - cov_new[t] = mult * cov_old[t]
> > -
> > - # Compute covariance inverse and cholesky decomposition.
> > - inv_cov_new[t] = sp.linalg.inv(cov_new[t])
> > - chol_cov_new[t] = sp.linalg.cholesky(cov_new[t])
> > -
> > - return mean_new, cov_new, inv_cov_new, chol_cov_new
> > + etas = np.zeros(T)
> > +
> > + del_ = self._hyperparams['del0']
> > + if self._hyperparams['pi2_cons_per_step']:
> > + del_ = np.ones(T) * del_
> > +
> > + fail = True
> >
> > maybe add comment for what fail is.
> > ------------------------------
> >
> > In python/gps/algorithm/traj_opt/traj_opt_utils.py
> > <https://github.com/cbfinn/gps/pull/80#discussion_r108503207>:
> >
> > >
> > -def traj_distr_kl(new_mu, new_sigma, new_traj_distr, prev_traj_distr):
> > +
> > +def traj_distr_kl(new_mu, new_sigma, new_traj_distr, prev_traj_distr,
> tot=True):
> >
> > update docstring
> > ------------------------------
> >
> > In python/gps/algorithm/ [...]

2017-03-30 03:00 UTC, zhangmarvin commented on python/gps/algorithm/traj_opt/config.py
> +    'min_eta': 1e-8,
It doesn't as far as I can tell, none of the other experiments I've tried seemed to come close to the old `min_eta` value.

2017-03-30 03:11 UTC, zhangmarvin commented on python/gps/algorithm/traj_opt/traj_opt_lqr_python.py
> +        if self._update_in_bwd_pass:
I can certainly work on that, but I think it's out of the scope of this PR.

2017-03-30 04:13 UTC, zhangmarvin commented
Ready for you to take another look, @cbfinn. Regarding the README: I feel that's a bit unnecessary, since reproducing the results in the paper is as simple as running the `mjc_gripper_pusher` and `mjc_door_opening` experiments, i.e., unlike SSRL, there's nothing complicated or unusual compared to normal GPS.

2017-03-30 18:43 UTC, cbfinn reviewed
Ok, agreed regarding a readme, though I think it would be good to change the experiment names to indicate the paper/method. For example, with rfgps, they prefixed the experiments with "icra" (https://github.com/cbfinn/gps/tree/rfgps/experiments).

Maybe prefix the experiment names with pilqr?

2017-03-30 18:43 UTC, cbfinn commented on python/gps/algorithm/traj_opt/traj_opt_lqr_python.py
> +        if self._update_in_bwd_pass:
Ok, sounds good.

2017-03-31 17:37 UTC, zhangmarvin commented
I've added 'pilqr' to the experiment names and done the remaining cleanup.

2017-03-31 20:46 UTC, cbfinn approved these changes

2017-03-31 20:47 UTC, cbfinn commented
LGTM!

2017-03-31 20:47 UTC, merged

2019-08-23 05:41 UTC, AswinRetnakumar commented
Hey is there a way to integrate pilqr algorithm with pr2 robot for moving the robot hand the a point by changing the hyperparameter values.